version: '3.9'

services:
  elasticsearch:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: elasticsearch-development
    restart: unless-stopped
    ports:
      - '9200:9200'
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - bootstrap.memory_lock=false
      - es.bootstrap.seccomp=false
      - es.bootstrap.ignore_system_bootstrap_checks=true
      - ELASTIC_PASSWORD=admin
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PASSWORD=admin
      - vm.max_map_count=262144
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - regenfass

networks:
  regenfass:
    name: regenfass
    driver: bridge
