version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: elasticsearch-development
    restart: unless-stopped
    ports:
      - '9200:9200'
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
      #- ELASTICSEARCH_USERNAME=admin
      #- ELASTICSEARCH_PASSWORD=admin
      - ELASTIC_PASSWORD=admin
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - regenfass

  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.3
    container_name: kibana-development
    restart: unless-stopped
    ports:
      - '5601:5601'
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - SERVER_NAME=kibana
      #- KIBANA_USERNAME=admin
      #- KIBANA_PASSWORD=admin
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - regenfass

networks:
  regenfass:
    name: regenfass
    driver: bridge
