version: '3.9'

services:
  elasticsearch:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: elasticsearch-development
    restart: unless-stopped
    ports:
      - '9200:9200'
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - vm.max_map_count=262144
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=admin
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PASSWORD=admin
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - regenfass

networks:
  regenfass:
    name: regenfass
    driver: bridge
